### PR TITLE
OKTA-509595 properly handle Okta Verify push reject

### LINKED ISSUE #168: Issue with Okta Verify Push Reject/Deny Response
### Describe the bug?

When user selects Okta Verify push and accepts the push request we are getting a proper response from PollAuthenticatorPushStatusAsync() sdk provided method but when push request is denied there is no return back(response) from PollAuthenticatorPushStatusAsync() API.

### What is expected to happen?

When user rejects/denied the push request we expect some response from PollAuthenticatorPushStatusAsync() API method like user denied the request and "continuepolling" value as false.

### What is the actual behavior?

When user denies the push request there is no response from PollAuthenticatorPushStatusAsync(). There is no exception/error as well. It is lost with no response even after timeout span.

### Reproduction Steps?

1. Perform primary authentication
2. Select Push factor - 
3. Send Push notification to user  - SelectChallengeAuthenticatorAsync() 
4. Upon getting the push request, reject the request from Okta verify application on mobile.
5. There is no response(get back) from polling - PollAuthenticatorPushStatusAsync();

### Additional Information?

_No response_

### .NET Version

.NET Core 3.1

### SDK Version

Okta.Idx.Sdk 2.2.1 (latest dotnet sdk)

### OS version

Windows 11 : 

BuildNumber                   Caption                               OSArchitecture       Version
22000                     Microsoft Windows 11 Pro               64-bit                 10.0.22000

Windows 10 : 

BuildNumber                   Caption                              OSArchitecture       Version
19044                     Microsoft Windows 10 Pro                64-bit               10.0.19044

### PR DESCRIPTION
**Pull request by bryanapellanes-okta**
In the video I first reject then accept the push request.
Fixes #168 

https://user-images.githubusercontent.com/63638027/187681696-977615a2-4dcb-403f-9fa8-2a1f826c5de4.mp4

### CODE REVIEW

File: samples/samples-aspnet/embedded-auth-with-sdk/embedded-auth-with-sdk/Controllers/OktaVerifyController.cs [hunk 1]
```diff
@@ -228,13 +230,25 @@ public async Task<ActionResult> ChallengePoll()
...
-                ClaimsIdentity identity = await AuthenticationHelper.GetIdentityFromTokenResponseAsync(_idxClient.Configuration, pollResponse.TokenInfo);
-                _authenticationManager.SignIn(new AuthenticationProperties(), identity);                
+                switch (pollResponse.AuthenticationStatus)
+                {
+                    case AuthenticationStatus.Success:
+                        ClaimsIdentity identity = await AuthenticationHelper.GetIdentityFromTokenResponseAsync(_idxClient.Configuration, pollResponse.TokenInfo);
+                        _authenticationManager.SignIn(new AuthenticationProperties(), identity);
+                        pollViewModel.Next = "/Home/Index";
+                        break;
+                    case AuthenticationStatus.Failed:
```
Comment (laura-rodriguez) [inline samples/samples-aspnet/embedded-auth-with-sdk/embedded-auth-with-sdk/Controllers/OktaVerifyController.cs:244]: Since this status seems specific to push notifications, I suggest renaming it to something else., for example, `PushFailed`.

**Review by laura-rodriguez — APPROVED** [review]
One minor comment, other than that LGTM.
